[build]
  functions = "netlify/functions"
  publish = "dist"

[dev]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
